coop/coop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers


from guide.views import area, ArtificialProblemViewSet,NaturalProblemViewSet,ProblemImageViewSet, AreaViewSet, SectorViewSet

from members.views import UserViewSet,MemberViewSet


admin.site.site_header='Galway Climbing Co-op admin'
admin.site.site_title='Galway Climbing Co-op admin'
#admin.site.index_title='Galway Climbing Co-op admin'


# django rest framework url routers for viewsets
router = routers.DefaultRouter()
router.register(r'artificialproblems',ArtificialProblemViewSet)
router.register(r'naturalproblems',NaturalProblemViewSet)
router.register(r'problemimages',ProblemImageViewSet)
router.register(r'users',UserViewSet)
router.register(r'members',MemberViewSet)
router.register(r'areas',AreaViewSet)
router.register(r'sectors',SectorViewSet)



from guide.views import area_map



urlpatterns = [
    url(r'api/', include(router.urls)),
    url(r'api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',area_map,{'area_id':1}),
    url(r'^guide/', include('guide.urls',namespace="guide")),
    url(r'^home/', include('homepage.urls',namespace="homepage")),
    url(r'^members/auth/', include('members.urls')),
    # note that the (customised) templates for the auth views are in [BASE_DIR]/templates/registration
    url(r'^members/', include('members.urls',namespace="members")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

coop/guide/urls.py
from django.conf.urls import url

from guide import views



from guide.views import ArtificialProblemList



urlpatterns = [
    url(r'^index',views.index,name="index"),
    url(r'^area/(?P<areaid>\d+)',views.area,name="area"),
    url(r'^sector/(?P<sectorid>\d+)',views.sector,name="sector"),
    url(r'^area_map/(?P<area_id>\d+)',views.area_map,name="area_map"),
    url(r'^problem/(?P<id>[0-9]+)',views.problem,name="problem"),
    url(r'^problem/toggle/(?P<userid>[0-9]+)/(?P<problemid>[0-9]+)',views.toggle_problem_status,name="toggle"),
    url(r'^problem/getstatus/(?P<userid>[0-9]+)/(?P<problemid>[0-9]+)',views.get_problem_status,name="getstatus"),
    url(r'^submit/(?P<problem_type>(natural)|(artificial))',views.submitproblem,name="submit"),
    url(r'^update/(?P<problem_id>\d+)',views.submitproblem,name="update"),
    url(r'^problem_flag/(?P<problem_id>\d+)',views.problem_flag,name="problem_flag"),
    url(r'^artificialproblems/',ArtificialProblemList.as_view()),

    ]

coop/homepage/urls.py
from django.conf.urls import url
from homepage import views

urlpatterns = [
        url(r'^$',views.index,name='index'),
        url(r'^index',views.index,name='index'),
        url(r'^about',views.about,name='about'),
        ]

coop/members/urls.py
from django.conf.urls import url, include

from members import views


# override the default login to implement remember me
#from django.contrib.auth.views import login
#from django.contrib.auth.views import login,password_reset,password_change

from django.contrib.auth.views import password_reset





urlpatterns = [
    #url(r'password_reset',password_reset,{'template_name':'registration/my_password_reset_form.html'}),
    #url(r'password_change',password_change,{'template_name':'registration/my_password_change_form.html'}),
    url(r'^',include('django.contrib.auth.urls')),
    url(r'^profile/',views.profile,name='profile'),
    url(r'^my_artificial_problems/',views.my_artificial_problems,name='my_artificial_problems'),
    ]

coop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Galway Climbing Coop</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static "bootstrap/css/bootstrap.min.css"%}">
    <!--<link href="../../dist/css/bootstrap.min.css" rel="stylesheet">-->

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static "bootstrap/css/ie10-viewport-bug-workaround.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/starter-template.css" %}" rel="stylesheet">
    <link href="{% static "css/coop-guide.css" %}" rel="stylesheet">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><span class ="glyphicon glyphicon-home home-button"></span>Galway Climbing Co-op</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >Climbing Areas <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    {% for a in areas %}
                    <li> <a href="{% url "guide:area" a.id %}">{{a.name}}</a> </li>
                    {% endfor %}
                </ul>
            </li>
            <li><a href="{% url "homepage:about" %}">About</a></li>
            {% block navitems %} 
            <!--app can add nav items in this block -->
            {% endblock %}
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" >Welcome {{user.first_name}} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li> <a href="{% url "logout" %}?next={{request.path}}">Log out</a> </li>
                    <li> <a href="{% url "members:profile" %}">Profile</a> </li>
                </ul>
            </li>
            {% else %}
            <li>
            <a href="{% url "login" %}?next={{request.path}}">Log in</a>
            </li>
            {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">



        <div class="starter-template">
        {% block main %}
        <p> Welcome to the home of Galway climbing.
        </div>

        {% endblock %}

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static "bootstrap/js/bootstrap.min.js"%}"></script>
    <script src="{% static "js/coop.js"%}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>