coop/coop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers


from guide.views import area, ArtificialProblemViewSet,NaturalProblemViewSet,ProblemImageViewSet, AreaViewSet, SectorViewSet

from members.views import UserViewSet,MemberViewSet


admin.site.site_header='Galway Climbing Co-op admin'
admin.site.site_title='Galway Climbing Co-op admin'
#admin.site.index_title='Galway Climbing Co-op admin'


# django rest framework url routers for viewsets
router = routers.DefaultRouter()
router.register(r'artificialproblems',ArtificialProblemViewSet)
router.register(r'naturalproblems',NaturalProblemViewSet)
router.register(r'problemimages',ProblemImageViewSet)
router.register(r'users',UserViewSet)
router.register(r'members',MemberViewSet)
router.register(r'areas',AreaViewSet)
router.register(r'sectors',SectorViewSet)



from guide.views import area_map



urlpatterns = [
    url(r'api/', include(router.urls)),
    url(r'api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',area_map,{'area_id':1}),
    url(r'^guide/', include('guide.urls',namespace="guide")),
    url(r'^home/', include('homepage.urls',namespace="homepage")),
    url(r'^members/auth/', include('members.urls')),
    # note that the (customised) templates for the auth views are in [BASE_DIR]/templates/registration
    url(r'^members/', include('members.urls',namespace="members")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

coop/members/urls.py
from django.conf.urls import url, include

from members import views


# override the default login to implement remember me
#from django.contrib.auth.views import login
#from django.contrib.auth.views import login,password_reset,password_change

from django.contrib.auth.views import password_reset





urlpatterns = [
    #url(r'password_reset',password_reset,{'template_name':'registration/my_password_reset_form.html'}),
    #url(r'password_change',password_change,{'template_name':'registration/my_password_change_form.html'}),
    url(r'^',include('django.contrib.auth.urls')),
    url(r'^profile/',views.profile,name='profile'),
    url(r'^my_artificial_problems/',views.my_artificial_problems,name='my_artificial_problems'),
    ]

coop/members/models.py
from django.db import models
from django.core.mail import send_mail


from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    email = models.EmailField(unique=True)
    REQUIRED_FIELDS = ['username']
    USERNAME_FIELD = 'email'

    def set_password(self,*args,**kwargs):
        result = super(User,self).set_password(*args,**kwargs)
        try:
            send_mail(
                    'user update',
                    'User with email: {em}, username: {un}, first_name:{fn}, last_name:{ln} useupdated a password'.format(em=self.email,un=self.username,fn=self.first_name,ln=self.last_name),
                    'galwayclimberscoop@gmail.com',
                    ['galwayclimberscoop@gmail.com'],
                    fail_silently=True
                    )
        except:
            pass
        return result



class Member(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    notifications = models.BooleanField(default=True,help_text="enable/disable email notifications")
    def __str__(self):
        return "{fn} {ln}".format(fn=self.user.first_name,ln=self.user.last_name)

coop/members/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import user_passes_test

from rest_framework.permissions import IsAdminUser


from guide.models import ArtificialProblem



# Create your views here.



from rest_framework import viewsets

from members.models import User, Member
from members.serializers import UserSerializer, MemberSerializer

@user_passes_test(lambda u:hasattr(u,'member'))
def profile(request):
    member = request.user.member
    return render(request,'members/profile.html',
            {
                }
            )


class UserViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAdminUser,)
    queryset = User.objects.all()
    serializer_class = UserSerializer
    

class MemberViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAdminUser,)
    queryset = Member.objects.all()
    serializer_class = MemberSerializer
    


@user_passes_test(lambda u:hasattr(u,'member'))
def my_artificial_problems(request):
    order_by = request.GET.get('order_by','grade')
    queryset = ArtificialProblem.objects.filter(owner=request.user.member).order_by(order_by)
    return render(request,'members/my_artificial_problems.html',{
        'queryset':queryset,
        'ob':order_by,
        })

coop/members/templates/members/login.html
{% extends 'base.html' %}


{% block main %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}
<form method="post" action="{% url 'members:login' %}">
{% csrf_token %}
<table>
<tr>
<td>{{ form.username.label_tag }}</td>
<td>{{ form.username }}</td>
</tr>
<tr>
<td>{{ form.password.label_tag }}</td>
<td>{{ form.password }}</td>
</tr>
</table>
                                            <input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>
                                        {# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'members:password_reset' %}">Lost password?</a></p>
{% endblock %}

coop/members/templates/members/profile.html
{% extends 'base.html' %}

{% block main %}

This will be a member profile page. For now ...
<p>

<a class="btn btn-primary" href="{% url 'members:my_artificial_problems' %}">Problems submitted by you</a>


{% endblock %}