coop/coop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers


from guide.views import area, ArtificialProblemViewSet,NaturalProblemViewSet,ProblemImageViewSet, AreaViewSet, SectorViewSet

from members.views import UserViewSet,MemberViewSet


admin.site.site_header='Galway Climbing Co-op admin'
admin.site.site_title='Galway Climbing Co-op admin'
#admin.site.index_title='Galway Climbing Co-op admin'


# django rest framework url routers for viewsets
router = routers.DefaultRouter()
router.register(r'artificialproblems',ArtificialProblemViewSet)
router.register(r'naturalproblems',NaturalProblemViewSet)
router.register(r'problemimages',ProblemImageViewSet)
router.register(r'users',UserViewSet)
router.register(r'members',MemberViewSet)
router.register(r'areas',AreaViewSet)
router.register(r'sectors',SectorViewSet)



from guide.views import area_map



urlpatterns = [
    url(r'api/', include(router.urls)),
    url(r'api-auth/',include('rest_framework.urls',namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^$',area_map,{'area_id':1}),
    url(r'^guide/', include('guide.urls',namespace="guide")),
    url(r'^home/', include('homepage.urls',namespace="homepage")),
    url(r'^members/auth/', include('members.urls')),
    # note that the (customised) templates for the auth views are in [BASE_DIR]/templates/registration
    url(r'^members/', include('members.urls',namespace="members")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

coop/guide/urls.py
from django.conf.urls import url

from guide import views



from guide.views import ArtificialProblemList



urlpatterns = [
    url(r'^index',views.index,name="index"),
    url(r'^area/(?P<areaid>\d+)',views.area,name="area"),
    url(r'^sector/(?P<sectorid>\d+)',views.sector,name="sector"),
    url(r'^area_map/(?P<area_id>\d+)',views.area_map,name="area_map"),
    url(r'^problem/(?P<id>[0-9]+)',views.problem,name="problem"),
    url(r'^problem/toggle/(?P<userid>[0-9]+)/(?P<problemid>[0-9]+)',views.toggle_problem_status,name="toggle"),
    url(r'^problem/getstatus/(?P<userid>[0-9]+)/(?P<problemid>[0-9]+)',views.get_problem_status,name="getstatus"),
    url(r'^submit/(?P<problem_type>(natural)|(artificial))',views.submitproblem,name="submit"),
    url(r'^update/(?P<problem_id>\d+)',views.submitproblem,name="update"),
    url(r'^problem_flag/(?P<problem_id>\d+)',views.problem_flag,name="problem_flag"),
    url(r'^artificialproblems/',ArtificialProblemList.as_view()),

    ]

coop/guide/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.html import format_html

from members.mixins import PermissionMixin
from members.models import Member


# Create your models here.


class Area(models.Model,PermissionMixin):
    name=models.CharField(max_length=300,null=True,blank=True)
    description=models.TextField(null=True,blank=True)
    area_type=models.CharField(max_length=15,choices=(('natural','natural'),('artificial','artificial')),default='artificial')
    def video_count(self):
        return ProblemVideo.objects.filter(problem__area=self).count()
    def __str__(self):
        return self.name


class AreaImage(models.Model,PermissionMixin):
    area = models.ForeignKey(Area,null=True,blank=True)
    image_file = models.FileField(upload_to='uploads',blank=True,null=True)
    imagemapcode = models.TextField(null=True,blank=True)
    imagemap = models.FileField(upload_to='uploads',blank=True,null=True)

    def __str__(self):
        return "{ar}: {id}".format(ar=self.area.name,id=self.id)



class BaseProblem(models.Model,PermissionMixin):
    area=models.ForeignKey('Area',null=True,blank=True)
    FONT_GRADES=(
            ('?','?'),
            ('3','3'),
            ('3+','3+'),
            ('4','4'),
            ('4+','4+'),
            ('5','5'),
            ('5+','5+'),
            ('6A','6A'),
            ('6A+','6A+'),
            ('6B','6B'),
            ('6B+','6B+'),
            ('6C','6C'),
            ('6C+','6C+'),
            ('7A','7A'),
            ('7A+','7A+'),
            ('7B','7B'),
            ('7B+','7B+'),
            ('7C','7C'),
            ('7C+','7C+'),
            )
    grade=models.CharField(max_length=50,choices=FONT_GRADES,default='?',blank=True, help_text='We use the <a href="https://en.wikipedia.org/wiki/Grade_(bouldering)#Fontainebleau_grades" target="_blank">Font grading system</a> for bouldering problems')
    sector=models.ForeignKey('Sector',null=True,blank=True,help_text='See the area map to identify the correct sector name. If the problem crosses multiple sectors, use the sector of the first hold for your left hand.')
    description=models.TextField(blank=True,null=True)
    exists=models.BooleanField(default=True)
    approved=models.BooleanField(default=True)
    owner=models.ForeignKey(Member,null=True,blank=True,related_name='owned_problem_set')
    done_by = models.ManyToManyField(Member,blank=True)

    # all the logic to determine whether or not a problem should be visible
    # need to extend this to include a user argument. For example, some problems
    # should be visible to admins or to problems owners but no one else
    def visible(self):
    # returns a Boolean 
        unresolved_flags = self.problemflag_set.filter(resolved=False)
        result =  unresolved_flags.count()==0 and self.exists and self.approved
        return result

    def __str__(self):
        return str(self.id)

    # some helpers to make the admin more functional

    # methods that are used in the admin to help filter by problems
    # that have an enresolved flag
    def unresolved_flags(self):
        return self.problemflag_set.filter(resolved=False)

    def has_unresolved_flag(self):
        return self.unresolved_flags().count() >0

    # methods for embedding media in the admin
    # for the site this stuff should be in the templates
    
    # this returns a safe html fragment that can be used to display an image
    # in the admin change page
    def pictures(self):
        pic_list = self.problemimage_set.all()
        if len(pic_list)==0:
            return False

        ht=""
        for pic in pic_list:
            try:
                im_url = settings.MEDIA_URL+pic.image_file.name
            except:
                return 'upload a picture'
            ht += "<p><img src='{url}' width='100%'/>".format(url=im_url)
        return format_html(ht)



class ArtificialProblem(BaseProblem):
    date=models.DateField(null=True,blank=True,help_text='The date on which the problem was set (if known)')
    HOLDS_CHOICES = (
            ('Black','Black'),
            ('Blue','Blue'),
            ('Blue (Dark)','Blue (Dark)'),
            ('Brown','Brown'),
            ('Cappucino','Cappucino'),
            ('Green','Green'),
            ('Green (Dark)','Green (Dark)'),
            ('Green (Flouro)','Green (Flouro)'),
            ('Grey','Grey'),
            ('Mint','Mint'),
            ('Orange','Orange'),
            ('Pink','Pink'),
            ('Purple','Purple'),
            ('Red','Red'),
            ('Red (Dark)','Red (Dark)'),
            ('Red (Rust)','Red (Rust)'),
            ('White','White'),
            ('Wooden','Wooden'),
            ('Yellow','Yellow'),
            ('Yellow (Flouro)','Yellow (Flouro)'),
            ('N/A (see description)','N/A (see description)'),
            )
    holds=models.CharField(max_length=300,null=True,blank=True,verbose_name='hold colour',choices=HOLDS_CHOICES)
    setter=models.CharField(max_length=300,null=True,blank=True)
    set_by = models.ForeignKey(Member,null=True,blank=True)

class NaturalProblem(BaseProblem):
    name=models.CharField(max_length=300,null=True,blank=True)
    first_ascensionist=models.CharField(max_length=100,null=True,blank=True)


class Sector(models.Model):
    class Meta:
        ordering = ('name',)
    name = models.CharField(max_length=200,null=True,blank=True)
    area = models.ForeignKey(Area,null=True,blank=True)


    def __str__(self):
        return "{ar}: {se}".format(ar=self.area.name,se=self.name)


class ProblemImage(models.Model,PermissionMixin):
    problem = models.ForeignKey(BaseProblem,null=True)
    image_file = models.FileField(upload_to='uploads',blank=True,null=True)
    def __str__(self):
        return "Problem {pr}: {id}".format(pr=self.problem.id, id =self.id)

    # method for displaying in the admin 
    def display(self):
        if self.image_file.name:
            im_url = settings.MEDIA_URL+self.image_file.name
            ht = "<p><img src='{url}' width='100%'/>".format(url=im_url)
            return format_html(ht)
        else:
            return format_html('')



class Comment(models.Model,PermissionMixin):
    class Meta:
        ordering = ('-created',)
    text = models.TextField()
    problem = models.ForeignKey(BaseProblem,null=True,blank=True)
    member = models.ForeignKey(Member,null=True,blank=True)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.text
 
class ProblemVideo(models.Model,PermissionMixin):
    embed_code = models.CharField(max_length=1000)
    problem = models.ForeignKey(BaseProblem,null=True,blank=True)
    member = models.ForeignKey(Member,null=True,blank=True) 



class ProblemFlag(models.Model):
    problem = models.ForeignKey(BaseProblem,null=True,blank=True)
    ISSUE_CHOICES = (
            ('no longer exists','no longer exists'),
            ('description is inaccurate/unclear','description is inaccurate/unclear'),
            ('loose hold(s)','loose hold(s)'),
            ('other (give a description)','other (give a description)'),
            )
    issue = models.CharField(max_length=100,choices=ISSUE_CHOICES)
    decription = models.TextField(null=True,blank=True,help_text='a short description of the issue')
    member = models.ForeignKey(Member,null=True,blank=True) 
    resolved = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        try:
            return "id: {id}, {issue}".format(id=self.id,issue=self.issue)
        except:
            return "id: {id}, {issue}".format(id=self.id,issue='None')





class ProblemByMember(models.Model):
    member = models.ForeignKey(Member,on_delete=models.CASCADE,null=True)
    problem = models.ForeignKey(BaseProblem,on_delete=models.CASCADE,null=True)
    date = models.DateField(null=True,blank=True)

coop/guide/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin.widgets import AdminFileWidget

from guide.models import NaturalProblem,ArtificialProblem,ProblemVideo,Comment,Sector,ProblemImage,ProblemFlag


class ProblemByMemberForm(forms.Form):
    status = forms.ChoiceField(choices=(
        (0,'still working on it'),
        (1,'done it'),
        ),
        )
    pass


class ProblemVideoForm(ModelForm):
    class Meta:
        model = ProblemVideo
        fields = ['embed_code']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']


class AddArtificialProblemForm(ModelForm):
    def __init__(self,*args,**kwargs):
        q = Sector.objects.all()
        if 'area_id' in kwargs:
            q = q.filter(area__id=kwargs['area_id'])
            kwargs.pop('area_id')
        super(AddArtificialProblemForm,self).__init__(*args,**kwargs)
        self.fields['sector'].queryset=q

    class Meta:
        model = ArtificialProblem
        exclude = ['exists','setter','owner','approved','done_by']
        widgets = {
                'description':forms.Textarea(attrs={
                    'placeholder':'A brief description of the problem. e.g. Dark blue with yellow tape, sit start, no arete, match on the last hold'}),
                'date':forms.TextInput(attrs={
                    'type':'date'
                    }),
                }


    def clean(self):
        cleaned_data = super(AddArtificialProblemForm,self).clean()
        holds = cleaned_data.get('holds')
        description = cleaned_data.get('description')
        #print((holds,description))
        if holds==None and description=='':
            self._errors['']="You must either submit a description or pick a hold colour"
        print(self._errors)
        return cleaned_data



class AddNaturalProblemForm(ModelForm):
    def __init__(self,*args,**kwargs):
        q = Sector.objects.all()
        if 'area_id' in kwargs:
            q = q.filter(area__id=kwargs['area_id'])
            kwargs.pop('area_id')
        super(AddNaturalProblemForm,self).__init__(*args,**kwargs)
        self.fields['sector'].queryset=q

    class Meta:
        model = NaturalProblem
        exclude = ['exists','owner','setter','approved','done_by']


    def clean(self):
        cleaned_data = super(AddNaturalProblemForm,self).clean()
        description = cleaned_data.get('description')
        #print((holds,description))
        if description=='':
            self._errors['']="You must submit a description"
        print(self._errors)
        return cleaned_data



class ProblemImageInlineForm(forms.ModelForm):
    image_file = forms.FileField()

    class Meta:
        model = ProblemImage
        fields = ('image_file',)


class ProblemFlagForm(forms.ModelForm):
    class Meta:
        model = ProblemFlag
        exclude = ('problem','member','resolved','created')

coop/guide/templates/guide/area.html
{% extends "guide/base_problem_list.html" %}

{% load static %}

{% block main %}


    <h3>{{area.name}}</h3>
    <a class="btn btn-primary btn-lg" id="info-button" href ="{% url 'guide:area_map' area.id %}">Area info and map</a>
    <a href="{% url "guide:submit" area.area_type %}?area={{area.id}}&set_by={{request.user.member.id}}&date={% now "Y-m-d" %}" class="btn btn-primary btn-lg" role="button">Submit a new problem for this area</a>
    

    {{ block.super }}


{% endblock %}

coop/guide/templates/guide/artificialproblem_list.html
{% extends 'base.html' %}



{% load static %}

{% block main %}


<div class="container">

    <table class="table problem-list">
        <tr class="problem-list-header-row">
            <td class="col-md-1"><a href="{{request.path}}?order_by={% if ob == "grade" %}-{% endif %}grade">Grade</a></td>
            <td class="col-md-1"><a href="{{request.path}}?order_by={% if ob == "sector" %}-{% endif %}sector">Sector</a></td>
            <td class="col-md-1"><a href="{{request.path}}?order_by={% if ob == "artificialproblem__holds" %}-{% endif %}artificialproblem__holds">Holds</a></td>
        </tr>
        {% for prob in artificialproblem_list %}
        <tr data-toggle="collapse" data-target="#collapse{{prob.id}}" class="accordion-toggle problem-list-item">
            <td class="col-md-1 problem-grade" data="{{prob.grade}}"><div >{{prob.grade}}</div></td>
            <td class="col-md-4">{{prob.sector.name}}</td>
            <td class="col-md-7"> {{prob.holds}} </td>
        </tr>
        <tr id="collapse{{prob.id}}" class="accordion-body collapse">
            <td colspan="3">{{prob.description}} <a href="{% url "guide:problem" prob.id %}"><span class="glyphicon glyphicon-info-sign problem-info-sign"></span></a></td>
        </tr>
        {% endfor %}
    </table>

</div>


<script src="{% static "js/area.js" %}"></script>


{% endblock %}

coop/guide/templates/guide/base_problem_list.html
{% extends "base.html" %}

{% load static %}

{% block main %}


<div class="container">

   <p>
    <h4>
        Click on a problem for a detailed description.
    </h4>

    <table class="table table-hover problem-list">
        <thead class="problem-list-header-row">
            <th class="grade-column"><a href="{{request.path}}?order_by={% if ob == "grade" %}-{% endif %}grade">Grade</a></th>
            <th class=""><a href="{{request.path}}?order_by={% if ob == "sector__name" %}-{% endif %}sector__name">Sector</a></th>
            {% if area.area_type == 'artificial' %}
            <th class=""><a href="{{request.path}}?order_by={% if ob == "artificialproblem__holds" %}-{% endif %}artificialproblem__holds">Hold colour</a></th>
            <th class=""><a href="{{request.path}}?order_by={% if ob == "artificialproblem__date" %}-{% endif %}artificialproblem__date">Date</a></th>
            {% else %}
            <th class=""><a href="{{request.path}}?order_by=naturalproblem__name">Name</a></th>
            {% endif %}
            {% if request.user.member %}
            <th class="">Done</th>
            {% endif %}
        </thead>
        {% for prob in prob_list %}
        {% if prob.visible %}
        <tr class="clickable-row problem-row" onclick="rowClickHandler(this)" data-href="{% url "guide:problem" prob.id %}" title="{{prob.description}}">
            <td class="grade-column problem-grade" data="{{prob.grade}}"><div><strong>{{prob.grade}}</strong></div></td>
            <td class=""><div>{{prob.sector.name}}</div></td>
            {% if prob.artificialproblem %}
            <td class="">
                <div>{{prob.artificialproblem.holds}}</div>
            </td>
            <td class="">
                <div>{{prob.artificialproblem.date | date:"d-m-Y" }}</div>
            </td>
            {% elif prob.naturalproblem %}
            <td class="">
                <div>{{prob.naturalproblem.name}}</div>
            </td>
            {% else %}
            {%endif%}
            {% if request.user.member %}
            <td class=""><div><span class="done-by-count">({{prob.done_by.all.count}})</span> {% if request.user.member %} {% if request.user.member in prob.done_by.all %}<span class="glyphicon glyphicon-ok problem-member-done"></span>{% else %}<span class="glyphicon glyphicon-remove problem-member-notdone"></span>{%endif %} {%else %}  {% endif %}</div></td>
            {% endif %}
        </tr>
        {% endif %}
        {% endfor %}
    </table>

</div>


<script src="{% static "js/problemlist.js" %}"></script>

{% endblock %}

coop/guide/templates/guide/clickable_area_map.html
{% extends 'base.html' %}

{% load static %}



{% block main %}


<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<!--<script src="{% static 'js/imageMapResizer.min.js' %}"></script>-->
<script src="{% static 'js/jquery.imagemapster.js' %}"></script>


<h3>{{area.name}}</h3>
<p>
<a class="btn btn-primary btn-lg" href="{% url 'guide:area' area.id %}">All problems in this area</a>
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#commentsModal" >Recent comments ({{ most_recent_comments | length }})</button>
<div class="modal fade" id="commentsModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Recently commented problems</h4>
            </div>
            <div class="modal-body">
                <p>
                {% for c in most_recent_comments %}
                <p>
                <a href="{% url 'guide:problem' c.problem.id %}">Problem {{c.problem.id}}: {{c.member.user.first_name}} commented {{c.created | timesince }} ago</a> 
                </p>
                {% endfor %}


                </p> 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>






{{area.description}}


{% if area.areaimage_set.all.1 %}
<h3>Interactive Map of Sectors: Click on a Sector</h3>
{% else %}
<h4>Map of Sectors</h4>
{% endif %}



    {% for ai in area.areaimage_set.all %}
    <img width="100%" src ="{{ai.image_file.url}}" {% if ai.imagemap %}usemap="#imagemap{{ai.id}}"{% endif %}/><map name="imagemap{{ai.id}}">
        {{ ai.imagemapcode | safe }}
    </map>

    {% endfor %}


<script>
$('img').mapster('resize',
        function () {
            return this.width
        });
$('img').mapster({
    stroke: true,
    render_highlight: {
        strokeWidth: 1,
        fade: false
    },
    fillColor:'555555',
    strokeColor:'555555',
    fillOpacity: 0.5,
    clickNavigate:true,

});



</script>

{% endblock %}

coop/guide/templates/guide/index.html
{% extends "base.html" %}





{% block main %}


<div class="container">
    <h3>Climbing Areas</h3>
    <div class="panel-group">
        {% for ar in arlist %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <strong>{{ ar.name }}</strong> 
                </h3>
                <a data-toggle="collapse" href="#collapse{{ar.id}}" class="toggle-description">Info</a>
            </div>
            <div id="collapse{{ar.id}}" class="panel-collapse collapse">
                <div class="panel-body">
                    <dl>
                        <dt>Area description</dt>
                        <dd>{{ar.description}}</dd>
                        <dt>Number of problems posted</dt>
                        <dd>{{ar.baseproblem_set.count}} ({{ar.video_count}} videos posted)</dd>
                        
                    </dl>
                    <p><a href="{% url "guide:area" areaid=ar.id%}">View problems</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>



{% endblock %}

coop/guide/templates/guide/message.html
{% extends 'base.html' %}

{% block main %}

{{message}}

{% if next %}
<p>
<a class="btn btn-primary" role-"button" href="{{next}}">Continue</a>

{% endif %}

{% endblock %}

coop/guide/templates/guide/new_problem_list.html
{% extends 'base.html' %}


{% load problem_list %}

{% comment %}

context should provide 
object_list - a queryset object
column_list - ordered list of columns to display
ordering - uses the syntax of django admin ordering -  columns id by number and - for 

{% endcomment %}

{% block main %}

{% block problemlist %}

<table>
    <thead>

    </thead>

{% for object in object_list %}
    <tr>
        {% for col in column_list %}
        <td> {{ object | list_display:col }} </td>
        {% endfor %}
    </tr>
{% endfor %}
</table>

{% endblock %}

{% endblock %}

coop/guide/templates/guide/problem.html
{% extends "base.html" %}

{% load static %}

{% block main %}


<div class="problem-actions">
    {% if request.user.member %}
    <a href = "{% url 'guide:update' problem.id %}" class = "problem-update-link" data-toggle="tooltip" data-placement="bottom" title="Edit this problem"><span class="glyphicon glyphicon-edit"></span></a>
    {% endif %}
    <a href = "#" id = "comment-popover-button" data-toggle="popover" data-placement="bottom"><span class="glyphicon glyphicon-comment"></span></a>
    <div id="comment-popover-content" class="hide">
        {% if request.user.member %}
        <form method="post">
            {% csrf_token %}
            {{ commentform.text }}
        <p>
        <input type="hidden" name="post-type" value="comment"/>
        <input type="submit" class="btn btn-primary" value="Post comment"/>
        </form>
        {% else %}
        Log in to post a comment.
        {% endif %}
    </div>
    <a href = "{% url 'guide:problem_flag' problem.id %}" class = "problem-flag-link" data-toggle="tooltip" data-placement="bottom" title="Flag an issue with this problem"><span class="glyphicon glyphicon-flag"></span></a>
</div>
<p>



{% if request.user.member %}

<h3>Done this one?</h3>


<script src="{% static "js/problem.js" %}">
</script>
<p class="status-element">
{% if request.user.member in problem.done_by.all %}<span class="glyphicon glyphicon-ok problem-member-done"></span>{% else %}<span class="glyphicon glyphicon-remove problem-member-notdone"></span>{%endif %}
</p>
<span class="btn btn-primary"  onclick="toggleStatus({{request.user.id}},{{problem.id}})">Toggle done/not done</span>

{% endif %}


<h3>Problem Info</h3>
{% if problem.artificialproblem %}
<dl>
    <dt>Sector</dt>
    <dd>{{problem.sector}}</dd>
    <dt>Hold colour</dt>
    <dd>{{problem.artificialproblem.holds}}</dd>
    <dt>Description</dt>
    <dd>{{problem.description}}</dd>
    <dt>Grade</dt> 
    <dd>{{problem.grade}}</dd>
    <dt>Date</dt>
    <dd>{{problem.artificialproblem.date}}</dd>
    <dt>Set by</dt>
    {% if problem.artificialproblem.set_by %}
    <dd>{{problem.artificialproblem.set_by.user.first_name }} {{problem.artificialproblem.set_by.user.last_name }}</dd>
    {% else %}
    <dd>Unknown</dd>
    {% endif %}
</dl>
{% elif problem.naturalproblem %}
<dl>
    <dt>Sector</dt>
    <dd>{{problem.sector}}</dd>
    <dt>Name</dt>
    <dd>{{problem.naturalproblem.name}}</dd>
    <dt>Description</dt>
    <dd>{{problem.description}}</dd>
    <dt>Grade</dt> 
    <dd>{{problem.grade}}</dd>
    <dt>Rock Type</dt>
    <dd>{{problem.naturalproblem.rock_type}}</dd>
    <dt>First Ascensionist</dt>
    <dd>{{problem.naturalproblem.first_ascensionist}}</dd>
</dl>
{%else %}
{{ problem.description }}
{% endif %}


<h3>Comments</h3>

{% if problem.comment_set.all.count > 0 %}
{% for v in problem.comment_set.all %}
<p><strong>{{v.member.user.get_full_name}}:</strong> {{v.text }}
{% endfor %}

{% else %}
Be the first to comment on this problem
<p>

{% endif %}

{% if request.user.member %}
{% else %}
<p>Log in to comment on this problem.
{% endif %}


{% if problem.pictures %}

<h3>Pictures</h3>


{{ problem.pictures }}


{% endif %}


<h3>Videos</h3>

{% if problem.problemvideo_set.all.count > 0 %}

{% for v in problem.problemvideo_set.all %}

<p>Posted at 
<p>{{v.embed_code | safe }}


{% endfor %}

{% else %}

No videos have been posted for this problem

{% endif %}

{% if request.user.member %}

<p> To post a video for this problem, copy/paste the embed code into the form below

<form method="post">

    {% csrf_token %}

{{ videoform.embed_code }}
<p>
<p>
<input type="hidden" name="post-type" value="video"/>
<input type="submit" class="btn btn-primary" value="Post"/>

</form>

{% else %}

<p>Log in to post a video for this problem.

{% endif %}





{% endblock %}

coop/guide/templates/guide/problem_flag.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block main %}

{% if submission_accepted %}

The problem has been flagged and will not be visible to users until the issue has been dealt with 

<p>
<a class="btn btn-primary" href="{% url "guide:area" problem.area.id %}">Continue</a>



{% else %}

<h3>Flag an issue with this problem</h3>
<strong>
    Flagging a problem hides the problem description from ALL users until the issue is addressed. It should only be used for major issues. For minor issues (e.g. you disagree with the grade) use the comment box on the problem page to discuss. 
</strong>

<p>
<form method="post">

{% csrf_token %}

{{ form | crispy }}

<p>
<strong>
Are you sure?
</strong>
<p>
<a class="btn btn-primary" href="{% url "guide:problem" problem_id %}">Cancel</a>
<p>
<input type="submit" class = "btn btn-danger" value="Flag this problem">

</form>


{% endif %}





{% endblock %}

coop/guide/templates/guide/problem_submission.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block main %}




{{form.media}}

<form method="post" enctype="multipart/form-data">

    {% csrf_token %}

    <strong style="color:red;">
    {{ form.errors }}
    </strong>

    {{ form | crispy }}

<h3>Images for this problem</h3>
<p>If you like, you can add some images to the problem description. This may help to easily 
identify the problem and will also help us to easily identify which problems are no longer
current.
<p>
{{ fs|crispy }}


<input type="hidden" name="problem_type" value = "{{problem_type}}"/>

<p>
<input type="submit" class = "btn btn-primary" value="Save this problem">
</form>

{% endblock %}

coop/guide/templates/guide/sector.html
{% extends "guide/base_problem_list.html" %}

{% load static %}

{% block main %}


    <h3>{{area.name}}: {{sector.name}}</h3>
    <a class="btn btn-primary" id="info-button" href ="{% url 'guide:area_map' area.id %}">Area info and map</a>
    <a href="{% url "guide:submit" area.area_type %}?area={{area.id}}&sector={{sector.id}}&set_by={{request.user.member.id}}&date={% now "Y-m-d" %}" class="btn btn-primary" role="button">Submit a new problem for this sector</a>
    


    {{ block.super }}


{% endblock %}